# .air.worker.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "CGO_ENABLED=1 go build -o ./tmp/main-worker ./cmd/worker"
  bin = "tmp/main-worker"
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_dir = ["cmd", "internal"]
  exclude_dir = ["tmp", "vendor", "bin", ".git"]
  exclude_file = []
  delay = 1000
  kill_delay = "0s"
  send_interrupt = false
  stop_on_root = false
  poll = true              # Enable polling mode
  poll_interval = 500      # Poll every 500ms

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false